#
#
# UniversalVaults Configuration
# contributors: [ImproperIssues, VideoGameSmash12]
#
#
config:
  plugin:
    prefix: "§7[§bUni§3Vault§7]"
  archive:
    watermark: "This item is distributed from UniversalVaults!"
    max-nbt-length: 100000
    min-nbt-length: 120
  submission:
    cool-down: 10
    enabled: true
