name: UniVault
version: '${project.version}'
main: me.improperissues.univault.UniVault
api-version: 1.17
authors: [ ImproperIssues ]
description: A universal vault that can be accessed from anywhere in the server.
website: github.com/ItziSpyder
commands:
  vault:
    description: Opens a vault
    usage: §4Correct Usage >> §7/vault <page number>
  view:
    description: Opens a public shelf
    usage: §4Correct Usage >> §7/view <type> <page number>
  submit:
    description: Opens the public submission menu
    usage: §4Correct Usage >> §7/submit §cor §7/submit <delete> <item index>