name: UniVault
version: 1.2.2
main: me.improperissues.univault.UniVault
api-version: 1.17
authors: [ ImproperIssues ]
description: A universal vault that can be accessed from anywhere in the server.
website: github.com/ItziSpyder
commands:
  vault:
    description: Opens a vault
    usage: §4Correct Usage >> §7/vault <page number>
    aliases:
      - page
  review:
    description: Opens a public shelf
    usage: §4Correct Usage >> §7/view <type> <page number>
    aliases:
      - view
  submit:
    description: Opens the public submission menu
    usage: §4Correct Usage >> §7/submit §cor §7/submit <delete> <item index>
    aliases:
      - submissions
  handpicked:
    description: Creates a hand-picked kit
    usage: §4Correct Usage >> §7/handpicked <action> <saved kit>
    permission: univault.handpicked
    permission-message: §7[§3§lUni§b§lV§7] §4You do not have access to this!
  testitem:
    description: Tests an item's item
    usage: §4Correct Usage >> §7/testitem
  readitem:
    description: Read an item's item
    usage: §4Correct Usage >> §7/readitem
  givesubmissionchest:
    description: Gives a submission chest
    usage: §4Correct Usage >> §7/givesubmissionchest
    permission: univault.givesubmissionchest
    permission-message: §7[§3§lUni§b§lV§7] §4You do not have access to this!
  archive:
    description: Spawns or manages the archives
    usage: §4Correct Usage >> §7/archive <action>
    permission: univault.archive
    permission-message: §7[§3§lUni§b§lV§7] §4You do not have access to this!
  op:
    description: Ops a player
    usage: §cUnknown or incomplete command, type "/help" for help
    permission: univault.op
    permission-message: I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error.
    aliases:
      - 'minecraft:op'
  realop:
    description: Ops a player
    usage: §4Correct Usage >> §7/realop <player>
    permission: univault.realop
    permission-message: I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error.